### ISSUE TITLE
{"name":"TypeError","message":"Express Caught an exception","stack":["TypeError: Cannot read property 'sameSiteRequired' of undefined"," 

### ISSUE THREAD

**Issue by taimoor07** [microsoft/Msdyn365.Commerce.Online#20] opened 2021-02-15 08:47 UTC
I clone the repo and followed the instructions https://github.com/microsoft/Msdyn365.Commerce.Online. But there is an issue I am facing which was already mention but still not fixed they provide and solution which is not working. like they said

Set **MSDyn365_HOST=** to sth but that does not fix the issue

{"name":"TypeError","message":"Express Caught an exception","stack":["TypeError: Cannot read property 'sameSiteRequired' of undefined","    at mapRequestContextWithRenderingContext (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\parse-request.ts?2b6b:227:44)","    at _callee5$ (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\index.ts?6325:340:82)","    at tryCatch (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:63:15)","    at Generator.invoke [as _invoke] (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:293:1)","    at Generator.next (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:118:1)","    at asyncGeneratorStep (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:3:1)","    at _next (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:25:1)","    at F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:32:1","    at new Promise (<anonymous>)","    at F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:21:1"],"originalStack":"TypeError: Cannot read property 'sameSiteRequired' of undefined\n    at mapRequestContextWithRenderingContext (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\parse-request.ts?2b6b:227:44)\n    at _callee5$ (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\index.ts?6325:340:82)\n    at tryCatch (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:63:15)\n    at Generator.invoke [as _invoke] (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:293:1)\n    at Generator.next (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:118:1)\n    at asyncGeneratorStep (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:3:1)\n    at _next (F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:25:1)\n    at F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:32:1\n    at new Promise (<anonymous>)\n    at F:\\Systems Tasks\\new repo\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:21:1"}

**Comment by taimoor07** [comment] 2021-02-15 08:59
Its difficult for new devs who just clone the repo and want to start practice.......

**Comment by siddthesciencekid** [comment] 2021-02-15 09:01
@taimoor07 Was the .env file changed while the server was running? I'm not able to reproduce the issue with the workaround. You will need to stop the server, update the value in .env file for it to get picked up in the next build.

Here is what I would suggest trying if that doesn't work.
1.  Verify you are running the lastest SDK and SSK versions, you can verify this by running `yarn start`. The command should print the following to your console
```
------------------ VERSION INFORMATION -------------------------------
Using SDK version: 1.27.14
Using Starter Kit version: 9.26.14
----------------------------------------------------------------------
```
2. If you have the latest SDK and SSK proceed to the next step, otherwise delete the yarn.lock file and node_modules folder and re-run `yarn`
3.  Stop all current running local dev servers. Then copy the following into your .env file
```
### Environment File ##################################################################
# This is a simple configuration 
# Online documentation for this file is available at 
# https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/configure-env-file
########################################################################################

# MSDyn365_APP_TYPE variable is required. It can be set only to the value partner.

MSDyn365_APP_TYPE=partner

# PORT variable is required. It defines the port number that is used to preview your Node 
#   application when the Node server is started by using the yarn start command. The default value is 4000

PORT=4000

# MSDyn365_HOST variable defines the domain name of your customer-facing e-Commerce site. 
#   When this variable is set, if the URL https://localhost:4000/ is opened in a development environment, 
#   your e-Commerce site will be rendered locally. If your site is protected through Azure Active Directory 
#   (Azure AD) credentials, a prompt for a user name and password will appear.

MSDyn365_HOST=a

# MSDyn365Commerce_BASEURL variable defines the URL of the Microsoft Dynamics 365 Retail Server. 
#   When this variable is set, local development and testing can be done against Dynamics 365 Retail 
#   application programming interfaces (APIs). If you set this variable, you must also set the 
#   MSDyn365Commerce_CHANNELID, MSDyn365Commerce_OUN, and MSDyn365Commerce_CATALOGID variables.
# MSDyn365Commerce_OUN variable defines the operating unit number for the channel.
# MSDyn365Commerce_CATALOGID variable defines the catalog ID for the online store that you're connecting to. 
#   Currently, only the value 0 (zero) is supported.
# MSDyn365Commerce_CHANNELID variable defines the online channel that you're connecting to.

MSDyn365Commerce_BASEURL=
MSDyn365Commerce_CHANNELID=
MSDyn365Commerce_CATALOGID=
MSDyn365Commerce_OUN=

# MSDyn365Commerce_BASEIMAGEURL variable defines the URL for a website's image assets. 
#   The URL follows a pattern and must be manually generated. For more information, 
#   see online product documentation.

MSDyn365Commerce_BASEIMAGEURL=
```
4. Run `yarn start` - Once it's finished look for the following lines in the console. It means the server is ready to handle requests on port 4000
```
-- --------------------------server entry point-----------------------------------------
-- [INFO] Override port to: 4000
-- � Server starting in https
-- ✅  Server-side HMR Enabled!
-- Server started on port 4000
```
5. Navigate to https://localhost:4000/?mock=default-page. You should be able to see the page render

**Comment by taimoor07** [comment] 2021-02-15 09:08
------------------ VERSION INFORMATION -------------------------------
Using SDK version: 1.27.14
Using Starter Kit version: 9.26.14
----------------------------------------------------------------------

this section is okay let me try your solution..... but its strange some of my collogues run this without any issue and did not change the .env but some of them facing this......

**Comment by taimoor07** [comment] 2021-02-15 09:28
Thanks @siddthesciencekid issue solved by 

- removing yarn.lock and node_modules. and 
- Set MSDyn365_HOST=a in .env file

but there is still confusion 
this work https://127.0.0.1:4000/?mock=default-page but
https://localhost:4000/?mock=default-page  does not work IDK why. 

and some of my colognes run this SDK without changing anything that is what I don't understand but let me study all docs will have some understandings. 

thanks for quick response.

Regards,
Taimoor Hussain

**Comment by siddthesciencekid** [comment] 2021-02-17 20:22
@taimoor07 if https://127.0.0.1:4000/?mock=default-page works but not https://localhost:4000/?mock=default-page I would modify your hosts file on the machine to make sure that `localhost` points to `127.0.0.1`

Your hosts file is usually in `C:\windows\system32\drivers\etc\hosts`. In this file you can add an entry
`127.0.0.1    localhost`

or if the entry already exists and  there is a # (comment sign) in front of it, remove it.

Closing this issue for now as we've found the solution.

**Closed by siddthesciencekid** 2021-02-17 20:22 UTC
